tap "borkdude/brew"
tap "clojure-lsp/brew"
tap "clojure/tools"
tap "d12frosted/emacs-plus"
tap "nikitabobko/tap"
brew "ollama", restart_service: :changed
brew "borkdude/brew/babashka"
brew "borkdude/brew/clj-kondo"
brew "clojure-lsp/brew/clojure-lsp-native"
brew "clojure/tools/clojure"
brew "d12frosted/emacs-plus/emacs-plus@30", args: ["with-imagemagick", "with-savchenkovaleriy-big-sur-3d-icon", "with-xwidgets"]
cask "cljstyle"
cask "ghostty"
cask "istat-menus"
cask "itsycal"
cask "jordanbaird-ice"
cask "maccy"
cask "orbstack"
cask "raycast"
cask "rectangle"
cask "dash"
brew "ispell"
