#+TITLE: Emacs configuration
#+AUTHOR: Gueorgui Tcherednitchenko
#+EMAIL: gt@gueorgui.net
#+OPTIONS: toc:nil num:nil

This was _heavily_ inspired by what @hrs is doing with [[https://github.com/hrs/dotfiles/blob/master/emacs/.emacs.d/configuration.org][his own Emacs config]],
with a lot of code shamelessly lifted from it and reprefixed.

* Personal information

Not sure what this is useful for yet, but will probably come in handy for things
like Git and email.

#+BEGIN_SRC emacs-lisp
(setq user-full-name "Gueorgui Tcherednitchenko"
      user-mail-address "gt@gueorgui.net")
#+END_SRC

* User interface tweaks

** Fonts

Set the font. I like =Source Code Pro= from Adobe.

#+BEGIN_SRC emacs-lisp
;; (setq doom-font (font-spec :family "Source Code Pro" :size 13))
#+END_SRC

[[https://github.com/be5invis/Iosevka][Iosevka]] is nice too!

#+BEGIN_SRC emacs-lisp
(setq doom-font (font-spec :family "Iosevka" :size 13))
#+END_SRC

Set emoji font

#+BEGIN_SRC emacs-lisp
(setq doom-unicode-font
      (if IS-MAC
          (font-spec :family "Apple Color Emoji")
        (font-spec :family "Twitter Color Emoji"))
      )
#+END_SRC

** Theme

#+BEGIN_SRC emacs-lisp
(setq doom-theme 'doom-one)
#+END_SRC

** The escape key is too far

Bind =jj= to escape and increase the default delay

#+BEGIN_SRC emacs-lisp
(setq evil-escape-key-sequence "jj"
      evil-escape-delay 0.3)
#+END_SRC

** Frame title

The default isn't useful. This binds the title to the name of the current
Projectile project.

#+BEGIN_SRC emacs-lisp
(setq frame-title-format '((:eval (projectile-project-name))))
#+END_SRC

** Maximize frame on statup

There is almost never a case where I want my Emacs to start up and not take up
the whole screen.

#+BEGIN_SRC emacs-lisp
;; (add-to-list 'default-frame-alist '(fullscreen . maximized))
#+END_SRC

This snippet is from [[https://emacs.stackexchange.com/a/3008][this StackExchange answer]].

** Don't waste any space with unnecessary UI

#+BEGIN_SRC emacs-lisp
(tool-bar-mode 0)
(menu-bar-mode 0)
(scroll-bar-mode -1)
#+END_SRC

* Org-mode

** User interface tweaks

Replace ellipsis in org-mode with downward facing arrow

#+BEGIN_SRC emacs-lisp
(setq org-ellipsis " ⤵")
#+END_SRC
Many more things to come here, I think...

** Inline images

We want inline images displayed in our Org buffers

#+BEGIN_SRC emacs-lisp
(setq org-startup-with-inline-images t)
#+END_SRC

** Tasks, notes, journal, agenda

Explicitly specify the org directory, in case I need to change it later.

#+BEGIN_SRC emacs-lisp
(setq org-directory "~/org")

(defun org-file-path (filename)
  "Return the absolute address of an org file, given its relative name."
  (concat (file-name-as-directory org-directory) filename))

(setq org-inbox-file "~/Dropbox/org/inbox.org")
(setq org-index-file (org-file-path "index.org"))
(setq +org-capture-todo-file (org-file-path "work.org"))
(setq org-archive-location
      (concat (org-file-path "archive.org") "::* From %s"))
#+END_SRC

Utility function to copy items from inbox to index.

#+BEGIN_SRC emacs-lisp
(defun gt/copy-tasks-from-inbox ()
  (when (file-exists-p org-inbox-file)
    (save-excursion
      (find-file org-index-file)
      (goto-char (point-max))
      (insert-file-contents org-inbox-file)
      (delete-file org-inbox-file))))
#+END_SRC

Store personal tasks in the index, separate file for work tasks:

#+BEGIN_SRC emacs-lisp
(setq org-agenda-files (list org-index-file
                             (org-file-path "recurring-events.org")
                             (org-file-path "work.org")))
#+END_SRC

Add an =IN PROGRESS= state to TODOs.

#+BEGIN_SRC emacs-lisp
(setq org-todo-keywords
      '((sequence "TODO" "IN-PROGRESS" "|" "DONE")))
#+END_SRC

Hitting =C-c C-x C-s= will mark a todo as done and move it to an appropriate
place in the archive.

#+BEGIN_SRC emacs-lisp
(defun gt/mark-done-and-archive ()
  "Mark the state of and org-mode item as DONE and archive it."
  (interactive)
  (org-todo 'done)
  (org-archive-subtree))

(add-hook 'org-mode-hook
          '(lambda ()
             (local-set-key (kbd "C-c C-x C-s") 'gt/mark-done-and-archive)))
#+END_SRC

Add a timestamp to completed todos.

#+BEGIN_SRC emacs-lisp
(setq org-log-done 'time)
#+END_SRC

Prevent a task from being marked done if it contains unfinished tasks or
checklists.

#+BEGIN_SRC emacs-lisp
(setq org-enforce-todo-dependencies t)
(setq org-enforce-todo-checkbox-dependencies t)
#+END_SRC

Show two-weeks agenda, starting today.

#+BEGIN_SRC emacs-lisp
(setq org-agenda-span 14)
(setq org-agenda-start-on-weekday nil)
#+END_SRC

Start the calendar week on Monday.

#+BEGIN_SRC emacs-lisp
(setq calendar-week-start-day 1)
#+END_SRC

Hide the category prefix from tasks.

#+BEGIN_SRC emacs-lisp
(setq org-agenda-prefix-format '((agenda . " %i %?-12t% s")
                                 (todo . " %i ")
                                 (tags . " %i ")
                                 (search . " %i ")))
#+END_SRC

Personal agenda view

#+BEGIN_SRC emacs-lisp
(require 'org-habit)

(defun gt/org-skip-subtree-if-priority (priority)
  "Skip an agenda subtree if it has a priority of PRIORITY.

PRIORITY may be one of the characters ?A, ?B, or ?C."
  (let ((subtree-end (save-excursion (org-end-of-subtree t)))
        (pri-value (* 1000 (- org-lowest-priority priority)))
        (pri-current (org-get-priority (thing-at-point 'line t))))
    (if (= pri-value pri-current)
        subtree-end
      nil)))

(defun gt/org-skip-subtree-if-habit ()
  "Skip an agenda entry if it has a STYLE property equal to \"habit\"."
  (let ((subtree-end (save-excursion (org-end-of-subtree t))))
    (if (string= (org-entry-get nil "STYLE") "habit")
        subtree-end
      nil)))

(setq org-agenda-custom-commands
      '(("p" "Personal agenda"
         ((tags "PRIORITY=\"A\""
                ((org-agenda-skip-function '(org-agenda-skip-entry-if
                                             'todo '("DONE" "PENDING" "BLOCKED")))
                 (org-agenda-overriding-header "Today's high-priority tasks:")))
          (agenda "")
          (todo "TODO"
                ((org-agenda-skip-function '(or (gt/org-skip-subtree-if-priority ?A)
                                                (gt/org-skip-subtree-if-habit)))
                 (org-agenda-overriding-header "Other tasks:")))
          (todo "PENDING"
                ((org-agenda-skip-function '(gt/org-skip-if-priority ?A))
                 (org-agenda-overriding-header "Waiting to hear about these:")))))))
#+END_SRC

Set keyboard shortcut for opening agenda. This will also copy items from the
inbox.

#+BEGIN_SRC emacs-lisp
(defun gt/dashboard ()
  (interactive)
  (gt/copy-tasks-from-inbox)
  (org-agenda nil "p"))

(global-set-key (kbd "C-c d") 'gt/dashboard)
#+END_SRC

Refiling according to the document's hierarchy.

#+BEGIN_SRC emacs-lisp
(setq org-refile-use-outline-path t)
(setq org-outline-path-complete-in-steps nil)
#+END_SRC

** Capturing tasks

Task capture templates

#+BEGIN_SRC emacs-lisp
(setq org-capture-templates
      '(
        ("b" "Blog idea"
         entry
         (file "~/org/blog-ideas.org")
         "* %?\n")
        ("f" "Finished book"
         table-line
         (file "~/org/books-read.org")
         "| %^{Title} | %^{Author} | %u | %^{Rating} | %^{Notes}")
        ("v" "Travel log"
         table-line
         (file "~/org/travel.org")
         "| %^{Place} | %^{Country} | %^{Region} | %^{Date arrived}t | %^{Date left}t | %^{Notes}")
        ("c" "Coffee"
         table-line
         (file "~/org/coffee.org")
         "| %^{Day}t | %^{Beans brand} | %^{Country} | %^{Grams} | %^{Grinder setting} | %^{Seconds} | %^{Rating} | %^{Notes}")
        ("r" "Reading list"
         checkitem
         (file "~/org/reading-list.org"))
        ("w" "Watching list"
         checkitem
         (file "~/org/watching-list.org"))
        ("t" "Todo"
         entry
         (file+headline org-index-file "Inbox")
         "* TODO %?\n")
        ("n" "Personal notes" entry
         (file+headline +org-capture-notes-file "Inbox")
         "* %u %?\n%i\n%a" :prepend t)
        ("j" "Journal" entry
         (file+olp+datetree +org-capture-journal-file "Inbox")
         "* %U %?\n%i\n%a" :prepend t)
        ("z" "Business idea"
         entry
         (file "~/org/business-ideas.org")
         "* %?\n")

        ;; Will use {org-directory}/{+org-capture-projects-file} and store
        ;; these under {ProjectName}/{Tasks,Notes,Changelog} headings. They
        ;; support `:parents' to specify what headings to put them under, e.g.
        ;; :parents ("Projects")
        ("p" "Centralized templates for projects")
        ("pt" "Project todo" entry
         (function +org-capture-central-project-todo-file)
         "* TODO %?\n %i\n %a"
         :heading "Tasks"
         :prepend nil)
        ("pn" "Project notes" entry
         (function +org-capture-central-project-notes-file)
         "* %U %?\n %i\n %a"
         :heading "Notes"
         :prepend t)
        ("pc" "Project changelog" entry
         (function +org-capture-central-project-changelog-file)
         "* %U %?\n %i\n %a"
         :heading "Changelog"
         :prepend t)))
#+END_SRC

Switch to insert mode when starting an Org capture.

#+BEGIN_SRC emacs-lisp
(add-hook 'org-capture-mode-hook 'evil-insert-state)
#+END_SRC

** Key bindings

#+BEGIN_SRC emacs-lisp
(global-set-key (kbd "C-c l") 'org-store-link)
(global-set-key (kbd "C-c a") 'org-agenda)
(global-set-key (kbd "C-c c") 'org-capture)
#+END_SRC

Hit =C-c i= to quickly open the todo list

#+BEGIN_SRC emacs-lisp
(defun gt/open-index-file ()
  "Open the master org TODO list."
  (interactive)
  (gt/copy-tasks-from-inbox)
  (find-file org-index-file)
  (flycheck-mode -1)
  (end-of-buffer))

(global-set-key (kbd "C-c i") 'gt/open-index-file)
#+END_SRC

Hit =M-n= to quickly open up a capture template for a new todo.

#+BEGIN_SRC emacs-lisp
(defun org-capture-todo ()
  (interactive)
  (org-capture :keys "t"))

(global-set-key (kbd "M-n") 'org-capture-todo)
#+END_SRC

* Programming
** Global evil-matchit

Easily jump between beginning/end of blocks

#+BEGIN_SRC emacs-lisp
(global-evil-matchit-mode 1)
#+END_SRC

** Global indentation

2 spaces for everything, goddamnit.

#+BEGIN_SRC emacs-lisp
(setq-default standard-indent 2)
#+END_SRC

** JavaScript & friends

Force 2 spaces indentation for JavaScript, JSON.

#+BEGIN_SRC emacs-lisp
(setq-default js-indent-level 2)
#+END_SRC

Use =typescript-mode= for Typescript, rather than =web-mode=.

#+BEGIN_SRC emacs-lisp
(add-to-list 'auto-mode-alist '("\\.tsx?\\'" . typescript-mode))
#+END_SRC

Use =eslint= for Typescript.

#+BEGIN_SRC emacs-lisp
(defun gt/typescript-mode-setup ()
  "Custom setup for Typescript mode"
  (setq flycheck-checker 'javascript-eslint)
  )
(add-hook 'typescript-mode-hook 'gt/typescript-mode-setup)
#+END_SRC

#+RESULTS:
| gt/flycheck-use-eslint | +electric | init-typescript-mode | doom--setq-comment-line-break-function-for-typescript-mode-h | rainbow-delimiters-mode | evil-collection-typescript-mode-set-evil-shift-width | doom--enable-+javascript-npm-mode-in-typescript-mode-h | npm-mode | +javascript-init-lsp-or-tide-maybe-h | +evil-embrace-angle-bracket-modes-hook-h | +lookup | init--set-typescript-mode |

** CSS

2 spaces indentation again.

#+BEGIN_SRC emacs-lisp
(setq-default css-indent-offset 2)
#+END_SRC

** Web-mode

Use web-mode for Nunjucks templates.

#+BEGIN_SRC emacs-lisp
(add-to-list 'auto-mode-alist '("\\.njk\\'" . web-mode))
#+END_SRC

Use 2 spaces indentation for everything.

#+BEGIN_SRC emacs-lisp
(setq-default web-mode-markup-indent-offset 2)
(setq-default web-mode-css-indent-offset 2)
(setq-default web-mode-code-indent-offset 2)
#+END_SRC
** Ruby

Manually specify the path to Rubocop with RBEnv

#+BEGIN_SRC emacs-lisp
(setq flycheck-ruby-rubocop-executable "~/.rbenv/shims/rubocop")
#+END_SRC
* Writing and publishing

** Linting prose

Use [[http://proselint.com/][Proselint]] to lint text

#+BEGIN_SRC emacs-lisp
(require 'flycheck)

(flycheck-define-checker proselint
  "A linter for prose."
  :command ("proselint" source-inplace)
  :error-patterns
  ((warning line-start (file-name) ":" line ":" column ": "
            (id (one-or-more (not (any " "))))
            (message (one-or-more not-newline)
                     (zero-or-more "\n" (any " ") (one-or-more not-newline)))
            line-end))
  :modes (text-mode markdown-mode gfm-mode org-mode))

(add-to-list 'flycheck-checkers 'proselint)

(add-hook 'markdown-mode-hook #'flycheck-mode)
(add-hook 'gfm-mode-hook #'flycheck-mode)
(add-hook 'text-mode-hook #'flycheck-mode)
(add-hook 'org-mode-hook #'flycheck-mode)
#+END_SRC
* Email

Using Mu4e for email.

Add the relevant directory to the load-path.

#+BEGIN_SRC emacs-lisp
(eval-when-compile
  (add-to-list 'load-path "/usr/share/emacs/site-lisp/mu4e")
  (require 'use-package))
(use-package mu4e)
#+END_SRC

Use OfflineIMAP to fetch mail

#+BEGIN_SRC emacs-lisp
(setq +mu4e-backend 'offlineimap)
#+END_SRC

Configure accounts

#+BEGIN_SRC emacs-lisp
(set-email-account! "Fastmail"
  '((mu4e-sent-folder       . "/Fastmail/Sent")
    (mu4e-drafts-folder     . "/Fastmail/Drafts")
    (mu4e-trash-folder      . "/Fastmail/Trash")
    (mu4e-refile-folder     . "/Fastmail/Archive")
    (smtpmail-smtp-user     . "gt@gueorgui.net")
    (user-mail-address      . "gt@gueorgui.net")
    (mu4e-compose-signature . "https://gueorgui.net"))
  t)
#+END_SRC

And SMTP

#+BEGIN_SRC emacs-lisp
(setq smtpmail-default-smtp-server "smtp.fastmail.com"
      smtpmail-smtp-server "smtp.fastmail.com"
      smtpmail-smtp-service 465)
#+END_SRC
