#!/usr/bin/env bash
set -euo pipefail

INTERNAL="DP-2"
EXTERNAL=("DP-0" "DP-1")
source displays.`hostname`

if type autorandr 2>/dev/null; then
  autorandr laptop
fi

for DP in $EXTERNAL; do
  xrandr --output $DP --off
done

source xrandr.undock.`hostname`

# Move the relevant workspaces to the builtin laptop display
for W in $(seq 1 10); do
  i3-msg "workspace $W; move workspace to output $INTERNAL"
done

# Set colour profiles
~/.bin/set-color-profiles
