[theme]
# dark = "modus_vivendi"
# light = "modus_operandi_tinted"
dark = "wolf-alabaster-dark-bg"
light = "wolf-alabaster-light-bg"
fallback = "base16_terminal"

[editor]
cursorline = true
bufferline = "multiple"
end-of-line-diagnostics = "hint"
default-yank-register = "+"

[editor.auto-save]
focus-lost = true

[editor.file-picker]
hidden = false

[editor.inline-diagnostics]
cursor-line = "warning"
other-lines = "warning"

[editor.lsp]
display-messages = true
display-progress-messages = true
display-inlay-hints = true

[editor.cursor-shape]
insert = "bar"

[editor.indent-guides]
render = true
character = "▏"

[editor.statusline]
left = [
  "mode",
  "spinner"
]
center = [
  "file-modification-indicator",
  "file-name"
]
right = [
  "file-type",
  "diagnostics",
  "workspace-diagnostics",
  "position",
  "position-percentage",
  "file-encoding"
]
mode.normal = "🦊 NOR"
mode.insert = "🦄 INS"
mode.select = "🐧 SEL"

[keys.insert]
"C-c" = "normal_mode"
"C-g" = "normal_mode"
"j" = { j = "normal_mode" }

[keys.normal."["]
b = ":buffer-previous"

[keys.normal."]"]
b = ":buffer-next"

[keys.normal]
b = ":echo %sh{git show --no-patch --format='%%h (%%an: %%ar): %%s' $(git blame -p %{buffer_name} -L%{cursor_line},+1 | head -1 | cut -d' ' -f1)}"

