[[language]]
name = "clojure"
auto-format = true
formatter = { command = "cljstyle", args = ["pipe"] }
roots = ["deps.edn", "project.clj"]
[language-server.clojure-lsp]
command = "clojure-lsp"

[[language]]
name = "ruby"
scope = "source.rb"
injection-regex = "ruby"
file-types = ["rb", "rake", "ru", "gemspec", "jbuilder"]
roots = ["Gemfile", ".git"]
comment-token = "#"
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "haskell"
scope = "source.hs"
auto-format = true

[language-server]
biome = { command = "biome", args = ["lsp-proxy"] }

[[language]]
name = "javascript"
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome" ]
auto-format = true

[[language]]
name = "typescript"
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome" ]
auto-format = true

[[language]]
name = "tsx"
auto-format = true
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome" ]

[[language]]
name = "jsx"
auto-format = true
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome" ]

[[language]]
name = "json"
language-servers = [ { name = "vscode-json-language-server", except-features = [ "format" ] }, "biome" ]
